2024-09-09 09:17:31,004 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-09 09:17:31,004 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Configure stats pid to 29260
2024-09-09 09:17:31,004 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/.config/wandb/settings
2024-09-09 09:17:31,004 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/settings
2024-09-09 09:17:31,005 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-09 09:17:31,005 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-09 09:17:31,005 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:17:31,005 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:17:31,005 INFO    MainThread:29260 [wandb_init.py:_log_setup():524] Logging user logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_091730-7w63qlyq/logs/debug.log
2024-09-09 09:17:31,005 INFO    MainThread:29260 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_091730-7w63qlyq/logs/debug-internal.log
2024-09-09 09:17:31,006 INFO    MainThread:29260 [wandb_init.py:init():607] calling init triggers
2024-09-09 09:17:31,006 INFO    MainThread:29260 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-09 09:17:31,006 INFO    MainThread:29260 [wandb_init.py:init():657] starting backend
2024-09-09 09:17:31,006 INFO    MainThread:29260 [wandb_init.py:init():661] setting up manager
2024-09-09 09:17:31,021 INFO    MainThread:29260 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-09 09:17:31,023 INFO    MainThread:29260 [wandb_init.py:init():669] backend started and connected
2024-09-09 09:17:31,059 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-09 09:17:31,059 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1348] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-09 09:17:31,059 INFO    MainThread:29260 [wandb_init.py:init():764] updated telemetry
2024-09-09 09:17:31,093 INFO    MainThread:29260 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-09-09 09:17:36,027 WARNING MainThread:29260 [wandb_init.py:init():1229] interrupted
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 800, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-09-09 09:18:46,367 INFO    MainThread:29260 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-09 09:18:46,388 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Configure stats pid to 29260
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/.config/wandb/settings
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/settings
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_init.py:_log_setup():524] Logging user logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_091846-mttg3zpo/logs/debug.log
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_091846-mttg3zpo/logs/debug-internal.log
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_init.py:init():607] calling init triggers
2024-09-09 09:18:46,389 INFO    MainThread:29260 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-09 09:18:46,390 INFO    MainThread:29260 [wandb_init.py:init():657] starting backend
2024-09-09 09:18:46,390 INFO    MainThread:29260 [wandb_init.py:init():661] setting up manager
2024-09-09 09:18:46,393 INFO    MainThread:29260 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-09 09:18:46,399 INFO    MainThread:29260 [wandb_init.py:init():669] backend started and connected
2024-09-09 09:18:46,410 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-09 09:18:46,410 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1348] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-09 09:18:46,415 INFO    MainThread:29260 [wandb_init.py:init():764] updated telemetry
2024-09-09 09:18:46,591 INFO    MainThread:29260 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-09-09 09:18:58,597 WARNING MainThread:29260 [wandb_init.py:init():1229] interrupted
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 800, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-09-09 09:19:05,678 INFO    MainThread:29260 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-09 09:19:05,707 INFO    MainThread:29260 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-09 09:19:05,727 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-09 09:19:05,727 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Configure stats pid to 29260
2024-09-09 09:19:05,727 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/.config/wandb/settings
2024-09-09 09:19:05,727 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/settings
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_init.py:_log_setup():524] Logging user logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_091905-cr8uybh3/logs/debug.log
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_091905-cr8uybh3/logs/debug-internal.log
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_init.py:init():607] calling init triggers
2024-09-09 09:19:05,728 INFO    MainThread:29260 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-09 09:19:05,729 INFO    MainThread:29260 [wandb_init.py:init():657] starting backend
2024-09-09 09:19:05,729 INFO    MainThread:29260 [wandb_init.py:init():661] setting up manager
2024-09-09 09:19:05,735 INFO    MainThread:29260 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-09 09:19:05,735 INFO    MainThread:29260 [wandb_init.py:init():669] backend started and connected
2024-09-09 09:19:05,743 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-09 09:19:05,743 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1348] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-09 09:19:05,743 INFO    MainThread:29260 [wandb_init.py:init():764] updated telemetry
2024-09-09 09:19:05,768 INFO    MainThread:29260 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-09-09 09:19:06,128 ERROR   MainThread:29260 [wandb_init.py:init():823] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-09-09 09:19:06,129 ERROR   MainThread:29260 [wandb_init.py:init():1235] error in wandb.init()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 829, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-09-09 09:29:45,931 INFO    MainThread:29260 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-09 09:32:21,639 INFO    MainThread:29260 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-09 09:35:38,551 INFO    MainThread:29260 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-09-09 09:35:38,563 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-09-09 09:35:38,563 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Configure stats pid to 29260
2024-09-09 09:35:38,563 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/.config/wandb/settings
2024-09-09 09:35:38,563 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/settings
2024-09-09 09:35:38,563 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-09-09 09:35:38,563 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-09 09:35:38,564 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:35:38,564 INFO    MainThread:29260 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-09-09 09:35:38,564 INFO    MainThread:29260 [wandb_init.py:_log_setup():524] Logging user logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_093538-0t5df6iu/logs/debug.log
2024-09-09 09:35:38,564 INFO    MainThread:29260 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/gabrielslotnisky/Documents/GitHub/Proyecto2024/models/wandb/run-20240909_093538-0t5df6iu/logs/debug-internal.log
2024-09-09 09:35:38,564 INFO    MainThread:29260 [wandb_init.py:init():607] calling init triggers
2024-09-09 09:35:38,564 INFO    MainThread:29260 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-09 09:35:38,565 INFO    MainThread:29260 [wandb_init.py:init():657] starting backend
2024-09-09 09:35:38,565 INFO    MainThread:29260 [wandb_init.py:init():661] setting up manager
2024-09-09 09:35:38,579 INFO    MainThread:29260 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-09-09 09:35:38,582 INFO    MainThread:29260 [wandb_init.py:init():669] backend started and connected
2024-09-09 09:35:38,612 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1338] probe notebook
2024-09-09 09:35:38,612 INFO    MainThread:29260 [wandb_run.py:_label_probe_notebook():1348] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-09 09:35:38,612 INFO    MainThread:29260 [wandb_init.py:init():764] updated telemetry
2024-09-09 09:35:38,648 INFO    MainThread:29260 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-09-09 09:36:29,722 WARNING MsgRouterThr:29260 [router.py:message_loop():77] message_loop has been closed
2024-09-09 09:37:08,899 ERROR   MainThread:29260 [wandb_init.py:init():823] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-09-09 09:37:08,900 ERROR   MainThread:29260 [wandb_init.py:init():1235] error in wandb.init()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 829, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
